domain: sandbox.local

# Uncomment the following settings if using the AWS RKE2 terraform setup
# istio:
#   ingressGateways:
#     public-ingressgateway:
#       type: "NodePort"
#       nodePortBase: 30000

istio:
  enabled: true
  ingressGateways:
    passthrough-ingressgateway:
      type: "LoadBalancer"
  gateways:
    passthrough:
      ingressGateway: "passthrough-ingressgateway"
      hosts:
        - "*.sandbox.local"
      tls:
        mode: "PASSTHROUGH"
  keycloak:
    enabled: true

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

logging:
  enabled: false
  license:
    trial: false

eckoperator:
  enabled: false

monitoring:
  enabled: false
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi

fluentbit:
  enabled: false
  values:
    securityContext:
      privileged: true

gatekeeper:
  enabled: false
  values:
    replicas: 1
    controllerManager:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    audit:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
    violations:
      hostNetworking:
        match:
          excludedNamespaces:
          - metallb-system
      allowedDockerRegistries:
        parameters:
          repos:
            - registry1.dso.mil
            - registry.dso.mil
            - quay.io
            - docker.io

kyverno:
  values:
    replicaCount: 1

twistlock:
  enabled: false
  values:
    console:
      persistence:
        size: 256Mi

clusterAuditor:
  # -- Toggle deployment of Cluster Auditor.
  enabled: false

addons:
  vault:
    enabled: true
  argocd:
    enabled: false
      redis:
        master:
          persistence:
            enabled: false
        replica:
          replicaCount: 1
          persistence:
            enabled: false

  keycloak:
    enabled: false
    ingress:
      gateway: "passthrough"
    values:
      replicas: 1
      secrets:
        env:
          stringData:
            X509_CA_BUNDLE: "/etc/x509/https/cas.pem"
        certauthority:
          stringData:
            cas.pem: '{{ .Files.Get "resources/dev/dod_cas.pem" }}'
      extraVolumes: |-              
        - name: certauthority
          secret:
            secretName: {{ include "keycloak.fullname" . }}-certauthority
      extraVolumeMounts: |-
        - name: certauthority
          mountPath: /etc/x509/https/cas.pem
          subPath: cas.pem
          readOnly: true
