bases:
- ../base
configMapGenerator:
  - name: environment
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patchesStrategicMerge:
#  - secrets.enc.yaml
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta1
  kind: GitRepository
  metadata:
    name: bigbang
  spec:
    interval: 5m
# Use the following three lines to test a new version of Big Bang without affecting other environments
#    ref:
#      $patch: replace
#      tag: "1.13.0"
- |-
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: bigbang
  spec:
    interval: 5m
    postRenderers:
      - kustomize:
          patchesJson6902:
            - target:
                kind: Namespace
                version: v1
                name: keycloak
              patch:
                - op: add
                  path: /metadata/labels/k8s.twr.io~1imageswap
                  value: enabled